-- AlterTable
ALTER TABLE "MealPlan" ADD COLUMN     "calories" DOUBLE PRECISION,
ADD COLUMN     "carbs" DOUBLE PRECISION,
ADD COLUMN     "fat" DOUBLE PRECISION,
ADD COLUMN     "protein" DOUBLE PRECISION;
